language: python
sudo: required
dist: xenial
python:
    - "3.7"
install:
    - pip install .
    - pip install git+https://github.com/numpy/numpy-stubs.git
    - pip install pycodestyle mypy
script:
    - pytest
    - python -m mypy --strict --allow-untyped-decorators --allow-untyped-defs dere/
    - python -m pycodestyle --max-line-length=110 dere/
